<FitnessApp>:
    name: "FitnessApp"
    MDBottomNavigation:
        MDBottomNavigationItem:
            id: "calories_screen"
            name:"calories_screen"
            text:"Калории"
            icon: 'scale-bathroom'
            on_pre_enter: root.show_recommend()
            MDFloatLayout:
                orientation: "vertical"
                canvas.before:
                    Color:
                        rgba: 0.94,0.94,0.94,1
                    Rectangle:
                        pos: self.pos
                        size: self.size

                    Color:
                        rgba: app.theme_cls.accent_color
                    Line:
                        width: 5
                        rectangle: self.x, self.y, self.width, self.height

                MDStackLayout:
                    pos_hint: {"x":0,"top":0.7}
                    spacing: "20dp"
                    MDLabel:
                        id: calories_show
                        halign: "center"
                        color: 0,0,0,1
                        font_size:24
                        size_hint: 1,None
                        height: "100dp"
                    MDLabel:
                        id: proteins_show
                        halign: "center"
                        color: 0,0,0,1
                        font_size:16
                        size_hint: 0.33,None
                        height: "50dp"
                    MDLabel:
                        id: fats_show
                        halign: "center"
                        color: 0,0,0,1
                        font_size:16
                        size_hint: 0.33,None
                        height: "50dp"
                    MDLabel:
                        id: carbs_show
                        halign: "center"
                        color: 0,0,0,1
                        font_size:16
                        size_hint: 0.33,None
                        height: "50dp"
        FoodNavigationItem:
            needed_list: food_list
            helpButton: helpButton
            id: id_food_menu_screen
            name: "food_menu_screen"
            icon: "food-outline"
            selected_foods:selected_foods
            text: "Меню"
            on_pre_enter: self.add_forms()
            MDStackLayout:
                selected_foods:selected_foods
                MDLabel:
                    text: "Ваше меню"
                    padding_x: '15dp'
                    padding_y: 0
                    font_size: 20
                    color: 0,0,0,1
                    size_hint: 1,0.1
                    md_bg_color: app.theme_cls.accent_dark
                SelectedFoods:
                    id: selected_foods
                    halign: "center"
                    text: "-----Текущие калории здесь-----"
                    font_size: 18
                    color: 0,0,0,1
                    size_hint: 1,0.1
                    md_bg_color: 0.94,0.94,0.94,1
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 3
                            rectangle: self.x, self.y, self.width, self.height
                HelpButton:
                    id: helpButton
                    text: "Помощь"
                    size_hint: 1,0.1
                    md_bg_color: app.theme_cls.primary_dark
                MDScrollView:
                    do_scroll_y: True
                    do_scroll_x: False
                    MDStackLayout:
                        id: food_list
                        size_hint: 1, None
                        height: self.minimum_height

        MDBottomNavigationItem:
            id: "add_food_menu_screen"
            name:"add_food_menu_screen"
            icon: "food-apple"
            text:"Нов блюдо"
            MDStackLayout:
                TextInput:
                    id: name_input
                    hint_text: "Название"
                    size_hint: 1,None
                    height: "50dp"
                    multiline: False
                    selectAll: True
                TextInput:
                    id: calories_input
                    hint_text: "Ккал"
                    size_hint: 1,None
                    height: "50dp"
                    multiline: False
                    selectAll: True
                TextInput:
                    id: proteins_input
                    hint_text: "Белки"
                    size_hint: 1,None
                    height: "50dp"
                    multiline: False
                    selectAll: True
                TextInput:
                    id: fats_input
                    size_hint: 1,None
                    hint_text: "Жиры"
                    height: "50dp"
                    selectAll: True
                    multiline: False
                TextInput:
                    id: carbs_input
                    size_hint: 1,None
                    hint_text:"Углеводы"
                    height: "50dp"
                    multiline: False
                    selectAll: True
                MDRaisedButton:
                    text: "Подтвердить"
                    size_hint: None,None
                    size: "50dp","50dp"
                    on_release: root.submit_food_click()
                    md_bg_color: app.theme_cls.primary_dark
        SettingsNavItem:
            id: "settings_screen"
            current_age: age_input
            current_weight: weight_input
            current_height: height_input
            current_gender: gender_input
            name: "settings_screen"
            icon: "human-edit"
            text:"Настройки"
            MDBoxLayout:
                orientation: 'vertical'
                MDStackLayout:
                    size_hint: 1, 0.4
                    TextInput:
                        id: gender_input
                        size_hint: 1,None
                        height: "50dp"
                        hint_text: "Пол (м/ж)"
                        multiline: False
                        selectAll: True
                    TextInput:
                        id: age_input
                        size_hint: 1,None
                        height: "50dp"
                        hint_text: "Возраст"
                        multiline: False
                        selectAll: True
                    TextInput:
                        id: weight_input
                        size_hint: 1,None
                        height: "50dp"
                        hint_text: "Вес"
                        multiline: False
                        selectAll: True
                    TextInput:
                        id: height_input
                        size_hint: 1,None
                        height: "50dp"
                        hint_text: "Рост(в см)"
                        selectAll: True
                        multiline: False
                ButtonsDeficitChoice:
                    id: deficit_choice
                    orientation: "lr-tb"
                    spacing: dp(10)
                    size_hint: 1, 0.2
                    MDRaisedButton:
                        id: diet_down
                        size_hint: 0.33,None
                        height: "50dp"
                        text: "Дефицит"
                        md_bg_color: app.theme_cls.primary_dark
                        on_release: self.parent.on_button_pressed(self)
                    MDRaisedButton:
                        id: diet_normal
                        size_hint: 0.33,None
                        height: "50dp"
                        text: "Поддержка"
                        md_bg_color: app.theme_cls.primary_dark
                        on_release: self.parent.on_button_pressed(self)
                    MDRaisedButton:
                        id: diet_up
                        size_hint: 0.33,None
                        height: "50dp"
                        text: "Набор"
                        md_bg_color: app.theme_cls.primary_dark
                        on_release: self.parent.on_button_pressed(self)
                MDBoxLayout:
                    size_hint: 1, 0.3
                    MDRaisedButton:
                        pos_hint: {'x': 0.5,'y': 0.9}
                        text: "Подтвердить"
                        height: "20dp"
                        on_release: self.parent.parent.parent.submit_profile_click(str(age_input.text),str(weight_input.text),str(height_input.text),str(gender_input.text), deficit_choice)
                        md_bg_color: app.theme_cls.primary_dark
                MDRaisedButton:
                    height: "20dp"
                    margin: "30dp"
                    text: "Закончить день"
                    font_size: 20
                    size_hint: 1,None
                    on_release: app.end_day()
                    md_bg_color: app.theme_cls.accent_light

<AmountAskPopup>
    amountText: amountText
    auto_dismiss: False
    title: "Enter the amount"
    size_hint: 0.8, 0.3
    MDBoxLayout:
        orientation: "vertical"
        TextInput:
            id: amountText
            size_hint: 1, 0.5
        MDRaisedButton:
            text: "Confirm"
            size_hint: 0.5,0.5
            pos_hint: {"x":0.5,"y":1}
            font_size: 18
            on_release: root.send_popup_to_calcs(root.amountText.text)
            md_bg_color: app.theme_cls.primary_dark